services:
  - type: web
    name: druglab
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DRUGLAB_DATABASE_URL
        value: postgresql+psycopg://druglab_app:DrugLabApp2026x@ep-jolly-bonus-b3ccfxu6.c-4.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      - key: DATABASE_URL
        value: postgresql+psycopg://druglab_app:DrugLabApp2026x@ep-jolly-bonus-b3ccfxu6.c-4.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      - key: ENVIRONMENT
        value: production
      - key: EMBEDDING_MODEL
        value: druglab-vector-v1

